/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package basiclibrary;

import java.util.*;
import java.util.Random;

public class Library {


        public static int[] roll(int num){

          int []arr=new int[num];
          Random rm=new Random();
            for (int i = 0; i < arr.length; i++) {
                arr[i]=rm.nextInt(6) +1;
            }
        return  arr ;
        }

    public static boolean containsDuplicates(int []arr){
        for (int i = 0; i < arr.length; i++) {
            for (int j = i+1; j< arr.length; j++) {
                if (arr[i]== arr[j]){
                    return true;
                }
            }
        }
        return false;
    }
    public static  double averages(int []arr){
        int sum =0;
        for (int i : arr) {
            sum += i;
        }

        return (double) sum/arr.length;
    }
public static int[] lowAvg(int [][]arr){
int index=0;
            int sum;
           double minAvg=0.0;
           double avg;
    for (int i = 0; i < arr.length; i++) {
        sum=0;
        avg=0.0;
        for (int j = 0; j < arr[i].length; j++) {
            sum+=arr[i][j];

        }//End Secound for
        avg = (double) sum/arr[i].length;
        if (minAvg==0.0){
            minAvg=avg;

        }else if (avg <minAvg){
            index= i ;
//            System.out.println("minAvg "+ minAvg + "avg "+ avg );
            minAvg =avg;
            System.out.println("The Min Avarege="+ minAvg);
        }
    }//End Main for
int []newArr =new int[arr[index].length];
    for (int i = 0; i < arr[index].length; i++) {

        newArr[i]=arr[index][i];
    }
   return newArr;
}// end Function

    public static String maps(int [][]arr){

            int high=0 ;
            int min=0;
            Set <Integer> set=new HashSet<Integer>();
        for (int i = 0; i < arr.length; i++) {
            for (int j = 0; j < arr[i].length; j++) {
                set.add(arr[i][j]);
            }
        }
        for (Integer i : set) {
         if (high==0 && min==0){
             high=i;
             min=i;
         }else if(i>high){
             high=i;
         }else if (i<min){
             min =i;
         }
        }
        System.out.println("high: " + high);
        System.out.println("min: "+ min);
        for (int i = min+1; i < high; i++) {
            if (!set.contains(i)){
                System.out.println("Never saw temperature: " +i);
            }
        }
         return "high:"+String.valueOf(high) + " min: "+ String.valueOf(min);
    }

    public static String tally(List<String> arr){
            int count=1;
            String highVoteName="";
           Map<String,Integer> vot=new HashMap<String,Integer>();
        for (String name : arr) {
             if (!vot.keySet().contains(name)){
                 vot.put(name,1);
             }else {

                 count =  (int)vot.get(name);
                 count++;
                 vot.put(name,count);

             }
        }
            count=0;

        for(String i: vot.keySet())
        {
            System.out.println(i +"  "+ vot.get(i));
        } // this for for testing
              for (String s:vot.keySet())
              {
                  if (vot.get(s) > count){
                      count=vot.get(s);
                      highVoteName=s;
                  }

              }

            return highVoteName;
    }


    ////////////////////////Main Method /////////////
    ///////////////////////-------------////////////
    public static void main(String[] args) {


       int arr[]= roll(4);

        for (int i : arr) {
            System.out.println(i);
        }

        int duplictArr[]={1,2,3,14,3,4,5};
        System.out.println("Duplicate: "+containsDuplicates(duplictArr));
int mark[]={55,88,90,89,77,90};
        System.out.println("The AVG :" + averages(mark));

        // Daily average temperatures for Seattle, October 1-28 2017
        int[][] weeklyMonthTemperatures = {
                {66, 64, 58, 65, 71, 57, 60},
                {57, 65, 65, 70, 72, 65, 51},
                {55, 54, 60, 53, 59, 57, 61},
                {65, 56, 55, 52, 55, 62, 57},

        };
        String high;
      high=maps(weeklyMonthTemperatures);
        System.out.println(high);

//       int []newArray= lowAvg(weeklyMonthTemperatures);
//        for (int i : newArray) {
//            System.out.println(i);
//        }

            List<String> votes =new ArrayList<String>();
        votes.add("Bush");
        votes.add("Bush");
        votes.add("Bush");
        votes.add("Shrub");
        votes.add("Hedge");
        votes.add("Shrub");
        votes.add("Bush");
        votes.add("Hedge");
        votes.add("Bush");

        String winner= tally(votes);
        System.out.println(winner + " #####received the most votes!");

    }

}
