/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package basiclibrary;

import java.util.Random;

public class Library {


        public static int[] roll(int num){

          int []arr=new int[num];
          Random rm=new Random();
            for (int i = 0; i < arr.length; i++) {
                arr[i]=rm.nextInt(6) +1;
            }
        return  arr ;
        }

    public static boolean containsDuplicates(int []arr){
        for (int i = 0; i < arr.length; i++) {
            for (int j = i+1; j< arr.length; j++) {
                if (arr[i]== arr[j]){
                    return true;
                }
            }
        }
        return true;
    }
    public static  double averages(int []arr){
        int sum =0;
        for (int i : arr) {
            sum += i;
        }

        return (double) sum/arr.length;
    }
public static int[] lowAvg(int [][]arr){
int index=0;
            int sum;
           double minAvg=0.0;
           double avg;
    for (int i = 0; i < arr.length; i++) {
        sum=0;
        avg=0.0;
        for (int j = 0; j < arr[i].length; j++) {
            sum+=arr[i][j];

        }//End Secound for
        avg = (double) sum/arr[i].length;
        if (minAvg==0.0){
            minAvg=avg;

        }else if (avg <minAvg){
            index= i ;
//            System.out.println("minAvg "+ minAvg + "avg "+ avg );
            minAvg =avg;
            System.out.println("The Min Avarege="+ minAvg);
        }
    }//End Main for
int []newArr =new int[arr[index].length];
    for (int i = 0; i < arr[index].length; i++) {

        newArr[i]=arr[index][i];
    }
   return newArr;
}// end Function
    public static void main(String[] args) {


//       int arr[]= roll(4);
//
//        for (int i : arr) {
//            System.out.println(i);
//        }
//
//        int duplictArr[]={1,2,1,3,4,5,4};
//        System.out.println(containsDuplicates(duplictArr));
//int mark[]={55,88,90,89,77,90};
//        System.out.println("The AVG :" + averages(mark));

        // Daily average temperatures for Seattle, October 1-28 2017
        int[][] weeklyMonthTemperatures = {
                {66, 64, 58, 65, 71, 57, 60},
                {57, 65, 65, 70, 72, 65, 51},
                {55, 54, 60, 53, 59, 57, 61},
                {65, 56, 55, 52, 55, 62, 57},
                {14, 65, 76, 44, 32, 45, 65}
        };


       int []newArray= lowAvg(weeklyMonthTemperatures);
        for (int i : newArray) {
            System.out.println(i);
        }

    }

}
