/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package inheritance;

import java.util.HashSet;
import java.util.Set;

public class Library {
    public boolean someLibraryMethod() {
        return true;
    }

    public static void main(String[] args) {


           Restaurant r=new Restaurant("osama",5);
        try {
        System.out.println(r.toString());
Review m=new Review("compsit","osama",2);
            r.addReview(m);
            Review m1=new Review("compsit","osama",2);
            Review m2=new Review("compsit","osama",2);
r.addReview(m1);
r.addReview(m2);
            System.out.println(r.toString());
            Review mo=new Review("test","osama",2);
            r.addReview(m);
            Review m5=new Review("Test2","osama",2);
            Review m6=new Review("Test3","Aliya",2);

            Restaurant r2=new Restaurant("ahmad",3);
         r2.addReview(m5);
         r2.addReview(m6);
            System.out.println("R2"+r2.toString());
        }catch (Exception e){
              e.printStackTrace();
          }


    }
}
