/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package inheritance;

import java.util.HashSet;
import java.util.Set;

public class Library {
    public boolean someLibraryMethod() {
        return true;
    }

    public static void main(String[] args) {


           Restaurant r=new Restaurant("osama",30);
        try {
       //   System.out.println(r.toString());


              r.addReview(5,"osama","alali");

            System.out.println(r.toString());

            Restaurant r2=new Restaurant("Yaser",52);
            r2.addReview(3,"osama","alali");
            System.out.println(r.toString());
            System.out.println(r2.toString());
        }catch (Exception e){
              e.printStackTrace();
          }


    }
}
