/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package linter;

import org.junit.jupiter.api.Test;

import java.nio.file.Path;

import static org.junit.jupiter.api.Assertions.*;

class AppTest {
//    @Test void appHasAGreeting() {
//        App classUnderTest = new App();
//        assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
//    }
    @Test public void check(){
        String link="./src/test/resources/test.text";

        String exp=" Line 1: Missing semicolon.\n";
        assertEquals(exp,App.check(link));
    }
}
